class MainView:
    """
    CONTRACT / INTERFACE untuk Controller
    Controller tidak boleh tahu Qt
    """

    # ===== TABLE =====
    def update_table(self, model): ...
    
    # ===== LOG =====
    def append_logs(self, html_list: list): ...
    def clear_logs(self): ...
    def get_log_filter(self) -> str: ...

    # ===== PROFILE =====
    def update_profile_list(self, profiles): ...
    def get_selected_profile_id(self): ...

    # ===== SYSTEM STATE =====
    def set_system_state(self, running: bool): ...

    # ===== SUPERBAR =====
    def set_profile_name(self, name: str): ...
    def update_next_bell(self, time, name): ...

    # ===== UI ACTIONS =====
    def show_warning(self, title, msg): ...
    def show_info(self, title, msg): ...
    def ask_confirm(self, title, msg) -> bool: ...